source(file.path("tests", "helper_load.R"))

stopifnot(!exists("ng_shiny_app_dir", mode = "function", inherits = TRUE))
stopifnot(!exists("ng_run_shiny_app", mode = "function", inherits = TRUE))
stopifnot(!exists("ng_run_app", mode = "function", inherits = TRUE))

desc <- read.dcf(file.path(root, "DESCRIPTION"))[1, ]
deps <- paste(desc[c("Depends", "Imports", "Suggests", "Enhances")], collapse = "\n")
stopifnot(!grepl("\\bshiny\\b", deps, ignore.case = TRUE))

backend_app_dir <- file.path(root, "inst", "shiny", "nextgenCrossDesign")
stopifnot(!dir.exists(backend_app_dir))

app_dir <- file.path(root, "shiny-frontend")
stopifnot(dir.exists(app_dir))
stopifnot(file.exists(file.path(app_dir, "app.R")))
stopifnot(file.exists(file.path(app_dir, "run_app.R")))
stopifnot(file.exists(file.path(app_dir, "DESCRIPTION")))
stopifnot(file.exists(file.path(app_dir, "www", "styles.css")))

app_source <- paste(readLines(file.path(app_dir, "app.R"), warn = FALSE), collapse = "\n")
stopifnot(grepl("nextgenCrossDesign", app_source, fixed = TRUE))
stopifnot(grepl("ng_backend_capability_registry", app_source, fixed = TRUE))
stopifnot(grepl("ng_preflight_input_tables", app_source, fixed = TRUE))
stopifnot(grepl("ng_add_multitrait_score", app_source, fixed = TRUE))
stopifnot(grepl("ng_ld_prune_markers", app_source, fixed = TRUE))
stopifnot(grepl("ng_add_balanced_usefulness_score", app_source, fixed = TRUE))
stopifnot(grepl("ng_optimize_balanced_usefulness", app_source, fixed = TRUE))
stopifnot(grepl("ng_pareto_mate_allocation", app_source, fixed = TRUE))
stopifnot(grepl("ng_allocate_family_sizes", app_source, fixed = TRUE))
stopifnot(grepl("ng_popvar_style_scores", app_source, fixed = TRUE))
stopifnot(grepl("ng_simplemating_select_crosses_native", app_source, fixed = TRUE))
stopifnot(grepl("ng_alphamate_style_select", app_source, fixed = TRUE))
stopifnot(grepl("operations-shell", app_source, fixed = TRUE))
stopifnot(grepl("workflow-sidebar", app_source, fixed = TRUE))
stopifnot(grepl("command-bar", app_source, fixed = TRUE))
stopifnot(grepl("workspace-main", app_source, fixed = TRUE))
stopifnot(grepl("workspace-inspector", app_source, fixed = TRUE))
stopifnot(grepl("stage_review", app_source, fixed = TRUE))
stopifnot(grepl("aria-label", app_source, fixed = TRUE))
stopifnot(grepl("metric_profile", app_source, fixed = TRUE))
stopifnot(grepl("gain_metric_col", app_source, fixed = TRUE))
stopifnot(grepl("diversity_metric_col", app_source, fixed = TRUE))
stopifnot(grepl("optimizer_family", app_source, fixed = TRUE))
stopifnot(grepl("optimizer_method", app_source, fixed = TRUE))
stopifnot(grepl("mip_contribution", app_source, fixed = TRUE))
stopifnot(grepl("repair_local", app_source, fixed = TRUE))
stopifnot(grepl("pareto_lambda_grid", app_source, fixed = TRUE))
stopifnot(grepl("family_size_method", app_source, fixed = TRUE))
stopifnot(grepl("external_surface", app_source, fixed = TRUE))
stopifnot(grepl("capability_stage", app_source, fixed = TRUE))
stopifnot(grepl("breeding_system", app_source, fixed = TRUE))
stopifnot(grepl("system_registry", app_source, fixed = TRUE))
stopifnot(grepl("all_method_registry", app_source, fixed = TRUE))
stopifnot(grepl("external_registry", app_source, fixed = TRUE))
stopifnot(grepl("metric_registry_table", app_source, fixed = TRUE))
stopifnot(grepl("pareto_frontier_table", app_source, fixed = TRUE))
stopifnot(grepl("family_size_summary_table", app_source, fixed = TRUE))
stopifnot(!grepl('type = "pills"', app_source, fixed = TRUE))

css_source <- paste(readLines(file.path(app_dir, "www", "styles.css"), warn = FALSE), collapse = "\n")
stopifnot(grepl(".operations-shell", css_source, fixed = TRUE))
stopifnot(grepl(".workflow-sidebar", css_source, fixed = TRUE))
stopifnot(grepl(".command-bar", css_source, fixed = TRUE))
stopifnot(grepl(".workspace-grid", css_source, fixed = TRUE))
stopifnot(grepl(".input-card", css_source, fixed = TRUE))
stopifnot(grepl(".sticky-actionbar", css_source, fixed = TRUE))
stopifnot(grepl("@media (max-width: 1100px)", css_source, fixed = TRUE))

app_desc <- read.dcf(file.path(app_dir, "DESCRIPTION"))[1, ]
app_deps <- paste(app_desc[c("Depends", "Imports")], collapse = "\n")
stopifnot(grepl("\\bshiny\\b", app_deps, ignore.case = TRUE))
stopifnot(grepl("\\bnextgenCrossDesign\\b", app_deps))

cat("shiny frontend boundary tests passed\n")
