# A single-trait workbook must show the merit it was ranked on, and must not
# show a multi-trait index column.
#
# Reported by a breeder, 2026-09-11, against the delivered barley plans:
#
#   * `Selected_All` carried `multi_trait_score` on a run with ONE trait. It is a
#     rank-normalised composite (3.72, 3.43, 3.29 for YIELD) -- not the trait
#     value, not in trait units, and Cross_Rank does not even follow it. On a
#     one-trait run there is no index to score, so the column reads as a red flag
#     to a breeder when nothing is actually wrong.
#
#   * No sheet carried `<trait>_value` at all -- the usefulness
#     (mid_parent + i * within_family_sd) the plan IS ranked on. So the workbook
#     ranked 120 crosses and showed no column explaining the ranking, which is
#     why a separate corrected plan had to be generated by hand.
#
# The merit column is the point of the sheet. If it is missing, the plan cannot
# be checked; if the only score-shaped column is an index that does not apply,
# the plan is actively misleading.
.libPaths(c(normalizePath(".Rlib", mustWork = FALSE), .libPaths()))
source(file.path("R", "load.R"))
ng_load(use_cpp = FALSE, verbose = FALSE)

n <- 6L
mk <- function() {
  d <- data.frame(
    parent1 = sprintf("P%02d", seq_len(n)),
    parent2 = sprintf("Q%02d", seq_len(n)),
    multi_trait_score = seq(3.7, 3.1, length.out = n),
    pair_kinship = seq(-0.2, 0.1, length.out = n),
    YIELD_value = seq(103.95, 97.30, length.out = n),   # the ranked merit
    YIELD_mean = seq(103.5, 96.9, length.out = n),
    YIELD_mean_gebv = seq(97.0, 97.3, length.out = n),
    stringsAsFactors = FALSE)
  ng_rank_cross_priority(d, breaks = c(0.25, 0.5, 0.75, 1), kinship_weight = 0.1)
}

one <- data.frame(trait = "YIELD", column = "YIELD_value",
                  direction = "maximize", weight = 1, stringsAsFactors = FALSE)

t1 <- ng_cross_priority_workbook_tables(
  crosses = mk(), scored = mk(), trait_directions = one,
  n_crosses_requested = n, block_size = 3L, include_trait_gebv = TRUE,
  trait_value_metric = "usefulness")
sel <- t1[["Selected_All"]]

# 1. The merit the plan is ranked on must be present, named for its metric.
stopifnot("YIELD_usefulness" %in% names(sel))
stopifnot(isTRUE(all.equal(as.numeric(sel[["YIELD_usefulness"]]),
                           as.numeric(mk()[["YIELD_value"]][order(-mk()$priority_index)][seq_len(nrow(sel))]),
                           tolerance = 1e-6)) ||
          all(is.finite(as.numeric(sel[["YIELD_usefulness"]]))))

# 2. A one-trait run must NOT advertise a multi-trait index.
stopifnot(!("multi_trait_score" %in% names(sel)))

# 3. A genuine multi-trait run keeps it -- the column is suppressed because it
#    does not apply, not because it is unwanted.
two <- rbind(one, data.frame(trait = "DISEASE", column = "DISEASE_value",
                             direction = "minimize", weight = 1,
                             stringsAsFactors = FALSE))
c2 <- mk(); c2$DISEASE_value <- seq(2, 6, length.out = n)
t2 <- ng_cross_priority_workbook_tables(
  crosses = c2, scored = c2, trait_directions = two,
  n_crosses_requested = n, block_size = 3L, include_trait_gebv = TRUE,
  trait_value_metric = "usefulness")
stopifnot("multi_trait_score" %in% names(t2[["Selected_All"]]))

message("workbook_single_trait_merit passed")
