// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ng_ld_prune_graph_cpp
IntegerVector ng_ld_prune_graph_cpp(NumericMatrix geno, int window, double r2_threshold, double maf_threshold, double ploidy);
RcppExport SEXP _nextgenCrossDesign_ng_ld_prune_graph_cpp(SEXP genoSEXP, SEXP windowSEXP, SEXP r2_thresholdSEXP, SEXP maf_thresholdSEXP, SEXP ploidySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type r2_threshold(r2_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type maf_threshold(maf_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type ploidy(ploidySEXP);
    rcpp_result_gen = Rcpp::wrap(ng_ld_prune_graph_cpp(geno, window, r2_threshold, maf_threshold, ploidy));
    return rcpp_result_gen;
END_RCPP
}
// ng_dh_recomb_pairs_cpp
DataFrame ng_dh_recomb_pairs_cpp(NumericMatrix geno, NumericVector beta, NumericVector beta_var, IntegerVector chr, NumericVector pos_cm, CharacterVector ids, CharacterVector pair_parent1, CharacterVector pair_parent2, double window_cm);
RcppExport SEXP _nextgenCrossDesign_ng_dh_recomb_pairs_cpp(SEXP genoSEXP, SEXP betaSEXP, SEXP beta_varSEXP, SEXP chrSEXP, SEXP pos_cmSEXP, SEXP idsSEXP, SEXP pair_parent1SEXP, SEXP pair_parent2SEXP, SEXP window_cmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_var(beta_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pos_cm(pos_cmSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pair_parent1(pair_parent1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type pair_parent2(pair_parent2SEXP);
    Rcpp::traits::input_parameter< double >::type window_cm(window_cmSEXP);
    rcpp_result_gen = Rcpp::wrap(ng_dh_recomb_pairs_cpp(geno, beta, beta_var, chr, pos_cm, ids, pair_parent1, pair_parent2, window_cm));
    return rcpp_result_gen;
END_RCPP
}
// ng_dh_recomb_pairs_full_posterior_cpp
DataFrame ng_dh_recomb_pairs_full_posterior_cpp(NumericMatrix geno, NumericVector beta, NumericVector beta_var_diag, NumericMatrix R_decay, NumericMatrix R_had_Sigma, IntegerVector pair_p1_zero, IntegerVector pair_p2_zero);
RcppExport SEXP _nextgenCrossDesign_ng_dh_recomb_pairs_full_posterior_cpp(SEXP genoSEXP, SEXP betaSEXP, SEXP beta_var_diagSEXP, SEXP R_decaySEXP, SEXP R_had_SigmaSEXP, SEXP pair_p1_zeroSEXP, SEXP pair_p2_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_var_diag(beta_var_diagSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R_decay(R_decaySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type R_had_Sigma(R_had_SigmaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_p1_zero(pair_p1_zeroSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_p2_zero(pair_p2_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(ng_dh_recomb_pairs_full_posterior_cpp(geno, beta, beta_var_diag, R_decay, R_had_Sigma, pair_p1_zero, pair_p2_zero));
    return rcpp_result_gen;
END_RCPP
}
// ng_dh_recomb_pairs_banded_cpp
DataFrame ng_dh_recomb_pairs_banded_cpp(NumericMatrix geno, NumericVector beta, NumericVector beta_var, IntegerVector band_i_zero, IntegerVector band_j_zero, NumericVector band_x, IntegerVector pair_p1_zero, IntegerVector pair_p2_zero);
RcppExport SEXP _nextgenCrossDesign_ng_dh_recomb_pairs_banded_cpp(SEXP genoSEXP, SEXP betaSEXP, SEXP beta_varSEXP, SEXP band_i_zeroSEXP, SEXP band_j_zeroSEXP, SEXP band_xSEXP, SEXP pair_p1_zeroSEXP, SEXP pair_p2_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_var(beta_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type band_i_zero(band_i_zeroSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type band_j_zero(band_j_zeroSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type band_x(band_xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_p1_zero(pair_p1_zeroSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_p2_zero(pair_p2_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(ng_dh_recomb_pairs_banded_cpp(geno, beta, beta_var, band_i_zero, band_j_zero, band_x, pair_p1_zero, pair_p2_zero));
    return rcpp_result_gen;
END_RCPP
}
// ng_bcm_posterior_sampler_cpp
NumericMatrix ng_bcm_posterior_sampler_cpp(NumericMatrix X_centered, NumericVector yc, NumericMatrix A_chol_upper, double sigma_e2, double lambda, int n_draws, int seed);
RcppExport SEXP _nextgenCrossDesign_ng_bcm_posterior_sampler_cpp(SEXP X_centeredSEXP, SEXP ycSEXP, SEXP A_chol_upperSEXP, SEXP sigma_e2SEXP, SEXP lambdaSEXP, SEXP n_drawsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X_centered(X_centeredSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yc(ycSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type A_chol_upper(A_chol_upperSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_e2(sigma_e2SEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type n_draws(n_drawsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ng_bcm_posterior_sampler_cpp(X_centered, yc, A_chol_upper, sigma_e2, lambda, n_draws, seed));
    return rcpp_result_gen;
END_RCPP
}
// ng_local_swap_cpp
IntegerVector ng_local_swap_cpp(NumericVector linear_gain, IntegerVector pair_p1_zero, IntegerVector pair_p2_zero, NumericMatrix parent_kinship, IntegerVector selected_zero, int max_per_parent, double lambda_group, double lambda_parent_use, int local_iter, int off_pool_size);
RcppExport SEXP _nextgenCrossDesign_ng_local_swap_cpp(SEXP linear_gainSEXP, SEXP pair_p1_zeroSEXP, SEXP pair_p2_zeroSEXP, SEXP parent_kinshipSEXP, SEXP selected_zeroSEXP, SEXP max_per_parentSEXP, SEXP lambda_groupSEXP, SEXP lambda_parent_useSEXP, SEXP local_iterSEXP, SEXP off_pool_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type linear_gain(linear_gainSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_p1_zero(pair_p1_zeroSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_p2_zero(pair_p2_zeroSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type parent_kinship(parent_kinshipSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type selected_zero(selected_zeroSEXP);
    Rcpp::traits::input_parameter< int >::type max_per_parent(max_per_parentSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_group(lambda_groupSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_parent_use(lambda_parent_useSEXP);
    Rcpp::traits::input_parameter< int >::type local_iter(local_iterSEXP);
    Rcpp::traits::input_parameter< int >::type off_pool_size(off_pool_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ng_local_swap_cpp(linear_gain, pair_p1_zero, pair_p2_zero, parent_kinship, selected_zero, max_per_parent, lambda_group, lambda_parent_use, local_iter, off_pool_size));
    return rcpp_result_gen;
END_RCPP
}
// ng_poly_dominance_scores_cpp
NumericMatrix ng_poly_dominance_scores_cpp(IntegerMatrix M, IntegerVector i1, IntegerVector i2, NumericMatrix mu, NumericMatrix varX, NumericMatrix EH, NumericMatrix varH, NumericMatrix covXH, NumericVector ba, NumericVector bd, NumericVector cen_a, NumericVector hbar, double intercept, bool has_dom);
RcppExport SEXP _nextgenCrossDesign_ng_poly_dominance_scores_cpp(SEXP MSEXP, SEXP i1SEXP, SEXP i2SEXP, SEXP muSEXP, SEXP varXSEXP, SEXP EHSEXP, SEXP varHSEXP, SEXP covXHSEXP, SEXP baSEXP, SEXP bdSEXP, SEXP cen_aSEXP, SEXP hbarSEXP, SEXP interceptSEXP, SEXP has_domSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i1(i1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i2(i2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type varX(varXSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type EH(EHSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type varH(varHSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type covXH(covXHSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ba(baSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cen_a(cen_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hbar(hbarSEXP);
    Rcpp::traits::input_parameter< double >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type has_dom(has_domSEXP);
    rcpp_result_gen = Rcpp::wrap(ng_poly_dominance_scores_cpp(M, i1, i2, mu, varX, EH, varH, covXH, ba, bd, cen_a, hbar, intercept, has_dom));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nextgenCrossDesign_ng_ld_prune_graph_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_ld_prune_graph_cpp, 5},
    {"_nextgenCrossDesign_ng_dh_recomb_pairs_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_dh_recomb_pairs_cpp, 9},
    {"_nextgenCrossDesign_ng_dh_recomb_pairs_full_posterior_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_dh_recomb_pairs_full_posterior_cpp, 7},
    {"_nextgenCrossDesign_ng_dh_recomb_pairs_banded_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_dh_recomb_pairs_banded_cpp, 8},
    {"_nextgenCrossDesign_ng_bcm_posterior_sampler_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_bcm_posterior_sampler_cpp, 7},
    {"_nextgenCrossDesign_ng_local_swap_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_local_swap_cpp, 10},
    {"_nextgenCrossDesign_ng_poly_dominance_scores_cpp", (DL_FUNC) &_nextgenCrossDesign_ng_poly_dominance_scores_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_nextgenCrossDesign(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
