# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ng_ld_prune_graph_cpp <- function(geno, window = 100L, r2_threshold = 0.9, maf_threshold = 0.01, ploidy = 2.0) {
    .Call(`_nextgenCrossDesign_ng_ld_prune_graph_cpp`, geno, window, r2_threshold, maf_threshold, ploidy)
}

ng_dh_recomb_pairs_cpp <- function(geno, beta, beta_var, chr, pos_cm, ids, pair_parent1, pair_parent2, window_cm = -1.0) {
    .Call(`_nextgenCrossDesign_ng_dh_recomb_pairs_cpp`, geno, beta, beta_var, chr, pos_cm, ids, pair_parent1, pair_parent2, window_cm)
}

ng_dh_recomb_pairs_full_posterior_cpp <- function(geno, beta, beta_var_diag, R_decay, R_had_Sigma, pair_p1_zero, pair_p2_zero) {
    .Call(`_nextgenCrossDesign_ng_dh_recomb_pairs_full_posterior_cpp`, geno, beta, beta_var_diag, R_decay, R_had_Sigma, pair_p1_zero, pair_p2_zero)
}

ng_dh_recomb_pairs_banded_cpp <- function(geno, beta, beta_var, band_i_zero, band_j_zero, band_x, pair_p1_zero, pair_p2_zero) {
    .Call(`_nextgenCrossDesign_ng_dh_recomb_pairs_banded_cpp`, geno, beta, beta_var, band_i_zero, band_j_zero, band_x, pair_p1_zero, pair_p2_zero)
}

ng_bcm_posterior_sampler_cpp <- function(X_centered, yc, A_chol_upper, sigma_e2, lambda, n_draws, seed) {
    .Call(`_nextgenCrossDesign_ng_bcm_posterior_sampler_cpp`, X_centered, yc, A_chol_upper, sigma_e2, lambda, n_draws, seed)
}

ng_local_swap_cpp <- function(linear_gain, pair_p1_zero, pair_p2_zero, parent_kinship, selected_zero, max_per_parent, lambda_group, lambda_parent_use, local_iter, off_pool_size) {
    .Call(`_nextgenCrossDesign_ng_local_swap_cpp`, linear_gain, pair_p1_zero, pair_p2_zero, parent_kinship, selected_zero, max_per_parent, lambda_group, lambda_parent_use, local_iter, off_pool_size)
}

ng_poly_dominance_scores_cpp <- function(M, i1, i2, mu, varX, EH, varH, covXH, ba, bd, cen_a, hbar, intercept, has_dom) {
    .Call(`_nextgenCrossDesign_ng_poly_dominance_scores_cpp`, M, i1, i2, mu, varX, EH, varH, covXH, ba, bd, cen_a, hbar, intercept, has_dom)
}

